/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoApp;


import controller.ProjectController;
import controller.TaskController;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import model.Project;
import model.task;
import util.connectionFactory;

public class App {
/*    public String getGreeting() {
        return "Hello World!";
    }*/

    public static void main(String[] args) throws SQLException  {
     //   System.out.println(new App().getGreeting());
        
        ProjectController proj = new ProjectController();

        /*Project project = new Project();
        project.setName("Projeto teste");
         project.setDescription("Alearorio");
        proj.save(project);*/

        //project.setId(1);
        //project.setName("Robinho");
        //proj.update(project);
        
        //List<Project> projects = proj.getAll();
        //System.out.println("Total de projetos " + projects.size());
        
        //proj.removeById(1);
        
        TaskController tasks = new TaskController ();
     
        task task =     new task ();
        
        task.setIdProject(3);
        task.setName("Primeiro teslskdjfslkdjfte159");
        task.setDescription("Teste de aplicacao15sdlfjsdlkfj9");
        task.setNotes("observacoessdkjfhskjdf159");
        task.setIsCompleted(false);
        task.setDeadline(new Date());
        tasks.save(task);
        
     /*  task.setIdProject(2);
        task.setName("Alterar telas de aplicacao");
        task.setIsCompleted(false);
        task.setDeadline(new Date(2023,6,2));
        task.setId(2);
        tasks.update(task);*/
       
       /*List <task> tak = tasks.getAll(2);
       System.out.println("Total de tarefas "+ tak.size());*/
       
 
       
    }
}
