/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Project;
import model.task;
import util.ButtomEdit;
import util.DeadlineColor;
import util.TaskTableModel;

/**
 *
 * @author robson
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
    ProjectController projectoController;
    TaskController taskController;
    
    DefaultListModel projectModel; 
    
    TaskTableModel taskTableModel;
    
    public MainScreen() {
          
        

        initComponents();
         initProjects();
         initComponentsModel();
         decoreteTableTasks();

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTasks = new javax.swing.JScrollPane();
        jTableTasks = new javax.swing.JTable();
        jPanel1ToolBar = new javax.swing.JPanel();
        jLabel1ToolBarTitle = new javax.swing.JLabel();
        jLabel2ToolbarSubtitle = new javax.swing.JLabel();
        jPanel2Projects = new javax.swing.JPanel();
        jLabel3ProjecsTitle = new javax.swing.JLabel();
        jLabelProjecstAdd = new javax.swing.JLabel();
        jPanelTasks = new javax.swing.JPanel();
        jLabelTasksTitle = new javax.swing.JLabel();
        jLabelTasksAdd = new javax.swing.JLabel();
        jPanelProjectsList = new javax.swing.JPanel();
        jScrollPaneListProjects = new javax.swing.JScrollPane();
        jListProjects = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanelEmptyList = new javax.swing.JPanel();
        jLabelEmptyListIcon = new javax.swing.JLabel();
        EmptyListTitle = new javax.swing.JLabel();
        jLabelEmptyListSubtitle = new javax.swing.JLabel();

        jScrollPaneTasks.setFont(new java.awt.Font("Keraleeyam", 0, 18)); // NOI18N

        jTableTasks.setFont(new java.awt.Font("Keraleeyam", 0, 18)); // NOI18N
        jTableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descricao", "Prazo", "Tarefa Concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTasks.setGridColor(java.awt.Color.white);
        jTableTasks.setRowHeight(50);
        jTableTasks.setRowSelectionAllowed(false);
        jTableTasks.setSelectionBackground(java.awt.Color.white);
        jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTasksMouseClicked(evt);
            }
        });
        jScrollPaneTasks.setViewportView(jTableTasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TodoApp (RSC)");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Frame3"); // NOI18N
        setSize(new java.awt.Dimension(600, 400));

        jPanel1ToolBar.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1ToolBar.setForeground(new java.awt.Color(0, 153, 102));

        jLabel1ToolBarTitle.setFont(new java.awt.Font("Keraleeyam", 0, 36)); // NOI18N
        jLabel1ToolBarTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1ToolBarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        jLabel1ToolBarTitle.setText(" ToDoApp");
        jLabel1ToolBarTitle.setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel2ToolbarSubtitle.setFont(new java.awt.Font("Keraleeyam", 0, 18)); // NOI18N
        jLabel2ToolbarSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2ToolbarSubtitle.setText("Anote tudo e nao esqueca de nada.");

        javax.swing.GroupLayout jPanel1ToolBarLayout = new javax.swing.GroupLayout(jPanel1ToolBar);
        jPanel1ToolBar.setLayout(jPanel1ToolBarLayout);
        jPanel1ToolBarLayout.setHorizontalGroup(
            jPanel1ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1ToolBarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2ToolbarSubtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1ToolBarLayout.setVerticalGroup(
            jPanel1ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ToolBarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1ToolBarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2ToolbarSubtitle)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2Projects.setBackground(java.awt.Color.white);
        jPanel2Projects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3ProjecsTitle.setFont(new java.awt.Font("Keraleeyam", 0, 24)); // NOI18N
        jLabel3ProjecsTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3ProjecsTitle.setText("Projetos");

        jLabelProjecstAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabelProjecstAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProjecstAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2ProjectsLayout = new javax.swing.GroupLayout(jPanel2Projects);
        jPanel2Projects.setLayout(jPanel2ProjectsLayout);
        jPanel2ProjectsLayout.setHorizontalGroup(
            jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3ProjecsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelProjecstAdd)
                .addContainerGap())
        );
        jPanel2ProjectsLayout.setVerticalGroup(
            jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProjecstAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel3ProjecsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelTasks.setBackground(java.awt.Color.white);
        jPanelTasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTasksTitle.setFont(new java.awt.Font("Keraleeyam", 0, 24)); // NOI18N
        jLabelTasksTitle.setForeground(new java.awt.Color(0, 152, 102));
        jLabelTasksTitle.setText("Tarefas");

        jLabelTasksAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabelTasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTasksAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTasksLayout = new javax.swing.GroupLayout(jPanelTasks);
        jPanelTasks.setLayout(jPanelTasksLayout);
        jPanelTasksLayout.setHorizontalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 568, Short.MAX_VALUE)
                .addComponent(jLabelTasksAdd)
                .addContainerGap())
        );
        jPanelTasksLayout.setVerticalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTasksLayout.createSequentialGroup()
                .addGroup(jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTasksAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(jPanelTasksLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTasksTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelProjectsList.setBackground(java.awt.Color.white);
        jPanelProjectsList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelProjectsList.setForeground(new java.awt.Color(0, 153, 102));

        jListProjects.setFont(new java.awt.Font("Keraleeyam", 0, 24)); // NOI18N
        jListProjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProjects.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jListProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProjectsMouseClicked(evt);
            }
        });
        jScrollPaneListProjects.setViewportView(jListProjects);

        javax.swing.GroupLayout jPanelProjectsListLayout = new javax.swing.GroupLayout(jPanelProjectsList);
        jPanelProjectsList.setLayout(jPanelProjectsListLayout);
        jPanelProjectsListLayout.setHorizontalGroup(
            jPanelProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneListProjects)
                .addContainerGap())
        );
        jPanelProjectsListLayout.setVerticalGroup(
            jPanelProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneListProjects, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanelEmptyList.setBackground(java.awt.Color.white);
        jPanelEmptyList.setMinimumSize(new java.awt.Dimension(800, 800));

        jLabelEmptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmptyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        EmptyListTitle.setFont(new java.awt.Font("Keraleeyam", 0, 18)); // NOI18N
        EmptyListTitle.setForeground(new java.awt.Color(0, 153, 102));
        EmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyListTitle.setText("Nenhuma tarefa por aqui! :-)");
        EmptyListTitle.setToolTipText("");

        jLabelEmptyListSubtitle.setFont(new java.awt.Font("Keraleeyam", 0, 18)); // NOI18N
        jLabelEmptyListSubtitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelEmptyListSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmptyListSubtitle.setText("Clique no botao \"+\" para adicionar uma tarefa");

        javax.swing.GroupLayout jPanelEmptyListLayout = new javax.swing.GroupLayout(jPanelEmptyList);
        jPanelEmptyList.setLayout(jPanelEmptyListLayout);
        jPanelEmptyListLayout.setHorizontalGroup(
            jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmptyListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmptyListSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEmptyListLayout.setVerticalGroup(
            jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabelEmptyListIcon)
                .addGap(18, 18, 18)
                .addComponent(EmptyListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmptyListSubtitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanelEmptyList, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2Projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2Projects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProjecstAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjecstAddMouseClicked
        // TODO add your handling code here:
        
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
        
        projectDialogScreen.addWindowListener(new WindowAdapter(){
            
            public void windowClosed (WindowEvent e){
                loadProject();
            }
        });
    }//GEN-LAST:event_jLabelProjecstAddMouseClicked

    private void jLabelTasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTasksAddMouseClicked

        
          int projecIndex = jListProjects.getSelectedIndex();
          if (projecIndex!=-1){
                      ProjectDialogTask projectDialogTask = new ProjectDialogTask(this, true);
        
                      
                   Project project =(Project) projectModel.get(projecIndex);
                   projectDialogTask.setProject(project);
                   projectDialogTask.setVisible(true);

                        
                projectDialogTask.addWindowListener(new WindowAdapter() {
                public void windowClosed(WindowEvent e) {
                    int projectIndex = jListProjects.getSelectedIndex();
                    Project project = (Project) projectModel.get(projectIndex);
                    loadTasks(project.getId());
                    

                                }
                        });
              
          }else {
            JOptionPane.showMessageDialog(rootPane, "Voce deve escolher um projeto para essa tarefa", "Erro", JOptionPane.ERROR_MESSAGE);
        }

        

        
    }//GEN-LAST:event_jLabelTasksAddMouseClicked

    private void jTableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTasksMouseClicked

        // TODO add your handling code here:
        
        int rowIndex = jTableTasks.rowAtPoint(evt.getPoint());
        int columnIndex = jTableTasks.columnAtPoint(evt.getPoint());
        task task = taskTableModel.getTask().get(rowIndex);

        switch (columnIndex){
            
            case 3:
                taskController.update(task);
                break;
                
              case 4:   
                  
      

                break;
                
              case 5:
                    
                  taskController.removeById(task.getId());
                  
                  int projectIndex = jListProjects.getSelectedIndex();
                    Project project = (Project) projectModel.get(projectIndex);
                    loadTasks(project.getId());

                  
                break;
                
            default:
                
        }
        
    }//GEN-LAST:event_jTableTasksMouseClicked

    private void jListProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProjectsMouseClicked
        // TODO add your handling code here:
        
        int projecIndex = jListProjects.getSelectedIndex(); 
        Project project = (Project ) projectModel.get(projecIndex);
        loadTasks(project.getId());
    }//GEN-LAST:event_jListProjectsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmptyListTitle;
    private javax.swing.JLabel jLabel1ToolBarTitle;
    private javax.swing.JLabel jLabel2ToolbarSubtitle;
    private javax.swing.JLabel jLabel3ProjecsTitle;
    private javax.swing.JLabel jLabelEmptyListIcon;
    private javax.swing.JLabel jLabelEmptyListSubtitle;
    private javax.swing.JLabel jLabelProjecstAdd;
    private javax.swing.JLabel jLabelTasksAdd;
    private javax.swing.JLabel jLabelTasksTitle;
    private javax.swing.JList<String> jListProjects;
    private javax.swing.JPanel jPanel1ToolBar;
    private javax.swing.JPanel jPanel2Projects;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEmptyList;
    private javax.swing.JPanel jPanelProjectsList;
    private javax.swing.JPanel jPanelTasks;
    private javax.swing.JScrollPane jScrollPaneListProjects;
    private javax.swing.JScrollPane jScrollPaneTasks;
    private javax.swing.JTable jTableTasks;
    // End of variables declaration//GEN-END:variables

public void decoreteTableTasks (){
    
    //Customizacao do Header table de tarefas
    
    jTableTasks.getTableHeader().setFont(new Font("Keraleeyam", Font.PLAIN,18));
    jTableTasks.getTableHeader().setBackground(new Color(0,153,102));
    jTableTasks.getTableHeader().setForeground(new Color (255,255,255));
    
    //Aplicando um filtro para as colunas Sorter
    jTableTasks.setAutoCreateRowSorter(true);
    jTableTasks.getColumnModel().getColumn(4).setCellRenderer(new ButtomEdit("edit"));
    
    
       jTableTasks.setAutoCreateRowSorter(true);
    jTableTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtomEdit("delete"));
    
    
    jTableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColor());
}

public void initProjects (){
    
    projectoController = new ProjectController();
    taskController = new TaskController();
}


public void initComponentsModel (){
    
    projectModel = new DefaultListModel();
    loadProject();
    
    taskTableModel = new TaskTableModel();
    jTableTasks.setModel(taskTableModel);
    
    if(!projectModel.isEmpty()){
        jListProjects.setSelectedIndex( 0);
        Project project = (Project)  projectModel.get(0);
        loadTasks(project.getId());
    }

}

public void loadTasks(int idProject){
        
    List <task> task = taskController.getAll(idProject);
    taskTableModel.setTask(task);
    showJTableTask(!task.isEmpty());
   
}

private void showJTableTask (boolean hasTask) {
    
    if (hasTask){
        if (jPanelEmptyList.isVisible()){
            jPanelEmptyList.setVisible(false);
            jPanel5.remove(jPanelEmptyList);
        }
        
        jPanel5.add(jScrollPaneTasks);
        jScrollPaneTasks.setVisible(true);
        jScrollPaneTasks.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        
         }else {
        
        if (jScrollPaneTasks.isVisible()){
            jScrollPaneTasks.setVisible(false);
            jPanel5.remove(jScrollPaneTasks);
        }
        
         jPanel5.add(jPanelEmptyList);
        jPanelEmptyList.setVisible(true);
        jPanelEmptyList.setSize(jPanel5.getWidth(), jPanel5.getHeight());
    }
    
    
}

public void loadProject (){
    
    List<Project> projects = projectoController.getAll();
    
    projectModel.clear();
    
    for (int i =0 ; i<projects.size(); i++){
        
        Project project = projects.get(i);
        projectModel.addElement(project);
        
    }
    jListProjects.setModel(projectModel);
}

public void projectIndex(){
    
       int projecIndex = jListProjects.getSelectedIndex();
          if (projecIndex!=-1){
                      ProjectDialogTask projectDialogTask = new ProjectDialogTask(this, true);
        
                      
                   Project project =(Project) projectModel.get(projecIndex);
                   projectDialogTask.setProject(project);
    
}
}

}
